= 第四部分 玩法

== 第十六章 运行时玩法基础系统

此处我简称(GFS),作者说是介于引擎和具体游戏之间的系统，业内没有惯用名称，所以他起了这个名，理论上，这一层与具体游戏无关，但是实际上很可能有关，但关系深浅不定。并且游戏的类型一定程度上决定了如何实现GFS

=== 16.1 玩法基础系统里的组件

大部分引擎的GFS虽然可能形式上不同, 但一般都包含以下几个子系统:

* 运行时游戏对象模型: 对game object model抽象的具体实现，一般是由游戏设计师通过编辑器实现
* 关卡管理和流式处理： 对虚拟世界里的内容，根据发生情况进行加载和卸载。在大部分引擎中，关卡数据是在游戏过程中流式加载到内存中的，因此，使其看上去像一个巨大的无缝世界(虽然事实上是打碎成分离的世界块来动态读取卸载的)
* 物体模型的实时更新：为了使物体可以自动产生各种行为，每个物体必须周期性的更新，此处即是引擎里各个系统交汇协调之处
* 消息和事件处理：大部分对象需要彼此交流，一般来讲会通过消息系统完成。物体间经常在游戏世界中通知状态变化，这种方式叫“事件”。所以，消息系统也叫事件系统
* 脚本： 要用类似C或C++来对游戏高层级的逻辑编程很麻烦。为了优化生产效率，允许快速迭代，并且让非开发者也能上手，游戏引擎一般会有一个脚本语言集成在内。这个语言可能是基于文本的，比如python或lua，或者可能是图形语言，比如UE的蓝图
* 目标和游戏流程管理： 这个子系统管理玩家的目标和游戏整体的流转。一般来讲是用序列，树，或图来描述。目标一般是按章节分组，特别是如果游戏是剧情驱动时。游戏流程管理系统，是用来管理游戏的整体流，比如追踪玩家的成就目标的达成情况，把玩家限制在某块区域直到完成某些目标时才放行之类的功能。一些设计师把其称为游戏的"脊梁"
+
[TIP]
====
**关于广义的图（Generalized Graph）：**
在游戏流程中，图允许任务节点之间存在非线性的交叉、闭环和多线并行，比单一的线性序列（Sequence）或树状分支（Tree）更为复杂。
====

运行时object model一般要提供以下功能:

* 动态产生和销毁: 比如血包会在捡起时要消失。这些对象可能是通过某种系统来管理内存，又或者是禁止动态内存分配
* 与引擎底层系统的关联： 对象与底层系统或多或少都有关联，比如大部分对象用可渲染的三角网格组成，是可被看到的，某些是具有例子效果的。还有很多会产生音效，或者有动画，碰撞等效果。GFS要保证对象能够访问引擎的这些系统
* 对物体行为的实时模拟
* 有能力去定义新的物体类型: 物体的定义应该允许在编辑器内定义和展现
* 物体的唯一id
* 对象搜索功能
* 对象引用功能
* 有限状态机支持：对象可以有多种状态，并由多种行为特征
* 网络复制
* 存储和加载，持久化功能： RTII，反射，存档

=== 16.2 运行时对象模型架构

主要有两种:

. 对象中心式架构：每个对象是以单个类的实例或数个相连的实例表示，每个对象含一组属性和行为，都会封装在实例的类(或多个类)中，游戏世界是对象的集合
+
[TIP]
====
其实就是OOP style建模的object model
====
. 属性中心式架构： 对象用id表示，对象的属性存到不同的表中，这些属性用id为键，而不是集中放置在某个类的实例里。属性是用类的实例表示。行为则是用某一些属性隐式地决定，比如：若某对象含HP属性，那么此对象就可以被攻击，扣血，死亡，又如，若对象含"MeshInstance"属性，就可以被渲染为物体的实例
+
[TIP]
====
其实就是DOP style建模的object model, ECS也是DOP的一种实现形式
====

两种方式各有优缺

==== 16.2.1 对象中心式架构

优点：直观，明确，大部分引擎都采用
缺点： 类层次结构会随着发展变得复杂臃肿，难以理解，维护，修改，分类标准一旦确定难以跨越和修改
+
[TIP]
====
有意思的是，此处大量提及UE就是这种结构的负面例子
====

这些缺点也有各种优化方式，此处略

==== 16.2.2 属性中心式架构

类似关系型数据库，把属性拆分成多个表，用id去关联，其中行为的实现要么放在属性里，要么通过脚本实现

===== 16.2.2.1 通过属性类来实现行为

比如：若某对象有Health属性，这个对象就可以受损，击杀等。属性对象还可以与其他对象的属性交互，比如通过消息系统发送事件完成

===== 16.2.2.2 通过脚本实现行为

每个游戏对象有一个比如scriptId的熟悉那个，若对象有这个属性，就可指定脚本，脚本里有行为的实现。但是核心属性一般还是由开发者硬编码的类实现，但是会开放给设计师一部分功能使用

===== 16.2.2.4 属性中心式架构的优缺点

优点:

* 内存高效：不会存储不需要的属性，而另一种架构下，对象里很可能有其他不必须的属性
* 属性的修改灵活，更方便支持运行时热加载，不用重新编译，只在要加新的属性类型时, 可能需要重启
* 更容易缓存友好： 同类型的数据是连续存储的(SOA)，由于硬件存取成本远高于指令的运算和执行成本，所以有利于性能