= 第二部分 引擎底层系统

== 第六章 引擎的各个支持系统

=== 6.2 内存管理

. 影响软件性能的几个要素： 使用的算法，算法的实现，对内存的使用方法
. 内存如何影响性能
.. 通过malloc或{cpp}全局new，是非常慢的操作，要么应该避免动态分配，要么用自定义内存分配器
.. 软件的性能被内存访问模式决定，内存小，成块连续可以很有效的被CPU使用，即便使用了高效的算法，若内存的布局不高效，性能也不好

==== 6.2.1 优化动态内存分配

通过malloc, free,或{cpp}的new, delete操作符，也称为堆分配，一般来讲是很慢的，原因有二:

. 堆内存是通用目的的设施，所以实现时是为了处理各类内存大小的分配，小到1字节，大到1gb,内存管理上性能开销大, 故malloc, free天生会很慢
. 在大部分操作系统中，调用malloc或free必须先从用户态转换为内核态，处理完请求后又切换回用户态，上下文切换的代价极其高昂

[sidebar]
.金句
--
最小化堆分配，决不要在快速执行的循环代码里用堆分配
--

为什么要自定义分配器,主要原因:

. 可实现预分配内存块，可以在用户态执行，避免操作系统的上下文切换
. 可根据内存分配策略，大小，用法，确定使用的分配模式，比通用型堆分配器更高效

===== 6.2.1.1 基于栈的分配器

实现简单，只需分配连续的一块内存(通过malloc/new 或byte数组(在执行程序的BSS段))，顶端维护一个指针，指针下的内存地址代表已用，指针之上的地址代表可用，初始化时指针会在栈的底部，每次分配只需把指针根据字节数上移，最近一次被分配的块可以被释放，只需把指针按这个块的大小往下移

内存不能以任意顺序释放，必须按分配的逆向顺序释放。最简单的限制方法就是不允许独立的一块自行释放。

一般来说会有一个函数返回一个当前栈顶的标志位，回滚函数会接收这个标志位来回滚，以保证操作正确，避免内存误操作。

书中的实现里，值得注意的是Marker用的是U32，而不是指针，可能考虑到不同系统的指针长度不一，这里统一为U32

====== 双端栈分配器

两个指针一个指栈顶，一个指栈底，内存使用更充分，内存碎片少

一个使用案例就是用来加载关卡，栈底指针用来加载和卸载关卡，栈顶指针用作临时的内存块，每帧使用。

===== 6.2.1.2 池分配器

分配很多个相同尺寸的小块内存，适合快速分配的同类型小对象，比如用于分配和释放矩阵，迭代器，链表里的链，或者mesh实例等

先预分配大块内存，内存尺寸是元素的整数倍，比如 4 x 4的矩阵就应该是64字节的整数倍，因为有16个4字节的元素

池里的每个元素黑背加入到链表结构的空闲列表中，当有分配的需求，只需要获取下一个空闲的元素并返回此元素，当元素被释放，只需把这个元素重新加回空闲列表。分配和释放都是O(1)的操作。

这个空闲列表存的是空闲内存块的内存地址

. 当元素尺寸大于指针尺寸， 指向下一个内存块的指针存到空闲内存块里面，以节省内存
. 当元素尺寸小于指针尺寸，可以用池元素的下标来实现链表

===== 6.2.1.3 对齐分配

===== 6.2.1.4 单帧和双缓冲分配

====== 单帧分配器

保留一块内存，用单向栈分配，在每帧开始时，栈顶指针移动到栈底，栈中分配在此进行并重复

注意内存不保留，不要在帧内留有指向栈里的指针

====== 单缓冲分配器

在帧i分配的内存可在i+1帧上使用，创建两个等尺寸的单帧分配器，然后在两者之间不断切换

用于缓存异步处理的信息，特别是多核家用机


=== 6.3 容器

==== 6.3.4 构建自定义容器类

许多引擎有自定义的容器类，特别是家用机和移动端，原因如下:

. 充分的控制权： 你可以控制数据结构的内存要求和分配，算法
. 更多的优化空间: 可根据特定硬件优化
. 可自由定制: 实现其他库没有的功能
. 消除额外的依赖: 不希望依赖其他公司或团队来维护，如果遇到问题还得等他们修复
. 对并发的控制更充分: 自定义线程安全策略，更精细灵活，上限高

=== 6.4 字符串

==== 6.4.1 String的问题

. string不是原子类型，并不是以字符的数组来实现的
. 做国际化的本地化转换时不变，比如不同语言的字体和书写方向
. 运行时性能代价高，比如对比和赋值操作要求O(n)扫描字符数组
.. 在作者测试中，strcmp()和strcpy()是整个引擎最耗性能的两个函数。通过优化调用就获得了巨幅帧数提升

==== 6.4.2 string类

std::string虽然方便，但是有难以被直接发现的性能开销。比如用std::string作为参数传递给函数时，如果使用不当，可能触发一次或多次拷贝构造。string的拷贝可能设计动态内存分配，让看上去无害的函数调用消耗比如几千次机器周期

由于std string数不清的问题，作者一般更推荐在运行时代码里避免使用，如果确实使用，要让所有程序员清楚代价

[sidebar]
.金句
--
总是通过引用来传递string对象，不要用值，后者会产生拷贝开销，多做性能测量，确保string没有成为主要的帧数下降问题！(原书就是感叹号😀)
--

另外一个类，用来存储系统路径的类: std::filesystem::path,假想的Path类会比纯C字符串数组增加巨量的价值，因为其支持各种跨平台相关字符的功能