= 第二部分 引擎底层系统

== 第六章 引擎的各个支持系统

=== 6.2 内存管理

. 影响软件性能的几个要素： 使用的算法，算法的实现，对内存的使用方法
. 内存如何影响性能
.. 通过malloc或{cpp}全局new，是非常慢的操作，要么应该避免动态分配，要么用自定义内存分配器
.. 软件的性能被内存访问模式决定，内存小，成块连续可以很有效的被CPU使用，即便使用了高效的算法，若内存的布局不高效，性能也不好

==== 6.2.1 优化动态内存分配

通过malloc, free,或{cpp}的new, delete操作符，也称为堆分配，一般来讲是很慢的，原因有二:

. 堆内存是通用目的的设施，所以实现时是为了处理各类内存大小的分配，小到1字节，大到1gb都得很好的支持, 内存管理上性能开销大, 所以malloc, free天生会很慢
. 在大部分操作系统中，调用malloc或free必须先从用户态转换为内核态，处理完请求后又切换回用户态，上下文切换的性能代价极其高昂

[sidebar]
.金句
--
最小化堆分配，决不要在快速执行的循环代码里用堆分配
--

为什么要自定义分配器,主要原因:

. 可实现预分配内存块，可以在用户态执行，避免操作系统的上下文切换
. 可根据内存分配策略，大小，用法，确定使用的分配模式，比通用型堆分配器更高效

===== 6.2.1.1 基于栈的分配器

实现简单，只需分配连续的一块内存(通过malloc/new 或byte数组(在执行程序的BSS段))，顶端维护一个指针，指针下的内存地址代表已用，指针之上的地址代表可用，初始化时指针会在栈的底部，每次分配只需把指针根据字节数上移，最近一次被分配的块可以被释放，只需把指针按这个块的大小往下移

内存不能以任意顺序释放，必须按分配的逆向顺序释放。最简单的限制方法就是不允许独立的一块自行释放。

一般来说会有一个函数返回一个当前栈顶的标志位，回滚函数会接收这个标志位来回滚，以保证操作正确，避免内存误操作。

书中的实现里，值得注意的是Marker用的是U32，而不是指针，可能考虑到不同系统的指针长度不一，这里统一为U32

====== 双端栈分配器

两个指针一个指栈顶，一个指栈底，内存使用更充分，内存碎片少

一个使用案例就是用来加载关卡，栈底指针用来加载和卸载关卡，栈顶指针用作临时的内存块，每帧使用。

===== 6.2.1.2 池分配器

分配很多个相同尺寸的小块内存，适合快速分配的同类型小对象，比如用于分配和释放矩阵，迭代器，链表里的链，或者mesh实例等

先预分配大块内存，内存尺寸是元素的整数倍，比如 4 x 4的矩阵就应该是64字节的整数倍，因为有16个4字节的元素

池里的每个元素会被加入到链表结构的空闲列表中，当有分配的需求，只需要获取下一个空闲的元素并返回此元素，当元素被释放，只需把这个元素重新加回空闲列表。分配和释放都是O(1)的操作。

这个空闲列表存的是空闲内存块的内存地址

. 当元素尺寸大于指针尺寸， 指向下一个内存块的指针存到空闲内存块里面，以节省内存
. 当元素尺寸小于指针尺寸，可以用池元素的下标来实现链表

===== 6.2.1.3 对齐分配

===== 6.2.1.4 单帧和双缓冲分配

====== 单帧分配器

保留一块内存，用单向栈分配，在每帧开始时，栈顶指针移动到栈底，栈中分配在此进行并重复

注意内存不保留，不要在帧内留有指向栈里的指针

====== 单缓冲分配器

在帧i分配的内存可在i+1帧上使用，创建两个等尺寸的单帧分配器，然后在两者之间不断切换

用于缓存异步处理的信息，特别是多核家用机

=== 6.3 容器

==== 6.3.4 构建自定义容器类

许多引擎有自定义的容器类，特别是家用机和移动端，原因如下:

. 充分的控制权： 你可以控制数据结构的内存要求和分配，算法
. 更多的优化空间: 可根据特定硬件优化
. 可自由定制: 实现其他库没有的功能
. 消除额外的依赖: 不希望依赖其他公司或团队来维护，如果遇到问题还得等他们修复
. 对并发的控制更充分: 自定义线程安全策略，更精细灵活，上限高

=== 6.4 字符串

==== 6.4.1 String的问题

. string不是原子类型，并不是以字符的数组来实现的
. 做国际化的本地化转换时不变，比如不同语言的字体和书写方向
. 运行时性能代价高，比如对比和赋值操作要求O(n)扫描字符数组
.. 在作者测试中，strcmp()和strcpy()是整个引擎最耗性能的两个函数。通过优化调用就获得了巨幅帧数提升

==== 6.4.2 string类

std::string虽然方便，但是有难以被直接发现的性能开销。比如用std::string作为参数传递给函数时，如果使用不当，可能触发一次或多次拷贝构造。string的拷贝可能涉及动态内存分配，让看上去无害的函数调用可能消耗几千次机器周期

由于st::string数不清的问题，作者一般更推荐在运行时代码里避免使用，如果确实使用，要让所有程序员清楚代价

[sidebar]
.金句
--
总是通过引用来传递string对象，不要用值，后者会产生拷贝开销，多做性能测量，确保string没有成为主要的帧数下降问题！(原书此处就是用的感叹号😀)
--

另外一个类，用来存储系统路径的类: std::filesystem::path, 假想的Path类会比纯C字符串数组增加巨量的价值，因为其支持各种跨平台相关字符的功能

== 第七章 资源和文件系统

=== 7.1 文件系统

功能点:

* 操作文件名和路径
* 文件的打开，关闭，读，写
* 目录扫描
* 处理文件异步IO(用于流式读写)

== 7.2 资源管理器

每个游戏都会用多种资源(也被称为资产(assets)或媒体(media))来构建。比如网格，材质，纹理，着色器，动画，音频切片，关卡，碰撞元，物理参数等

其不单在离线工具创建资源时被管理，还需要在运行时被管理

在一些引擎中，资源管理是在一个中心化的子系统里统一管理，另一些引擎中，资源管理是分散在各处被使用

=== 7.2.1 离线资源管理和工具链

==== 7.2.1.2 资源数据库

资源数据库负责生成和管理资源的元数据，转换为引擎内部特定的二进制格式，必须提供下列基础功能:

* 处理多种类型的资源，处理方式尽量一致
* 能创建，删除新的资源
* 能查看和修改现存资源
* 能在硬盘上移动资源文件的位置
* 能支持资源之间的交叉引用
* 维持数据库内内交叉引用的完整性，执行常见操作后，还能保持完整性
* 保存版本历史，并记录改动日志
* 支持搜索

=== 7.2.2 运行时资源管理

==== 7.2.2.1 运行时资源管理的职责

* 确保统一资源在内存中只有一份副本
* 管理资源的生命周期，载入需要的资源，卸载不需要的资源
* 处理复合资源的载入
* 维护引用的完整性，包括资源内部的交叉引用关系和资源之间的交叉引用
* 管理资源载入后的内存，确保内存的分配合理
* 允许资源按类型，并在载入后进行自定义处理，又称为资源登录(login)或资源载入初始化(load-initializing)
* 一般会提供统一的接口来管理多种资源类型，资源管理器要易于扩展，比如支持更多类型的资源
* 支持流式或异步资源载入

==== 7.2.2.3 资源文件格式

纹理一般会存储为TGA，PNG， TIFF，JPEG, BMP, 或者标准纹理压缩格式，如DirectX的S3, Maya或LightWave里的OBJ,COLLADA等

单一文件格式可存储多种不同类型的资产(复合资源)，如Granny SDK可以存储mesh, skeleton, skinny等数据

自定义文件格式的原因:

. 引擎内部需要的一些信息可能没有标准格式可以提供
. 想在运行前处理资源，用来降低运行时载入和处理资源的时间开销
. 想让资源的数据遵从特定的内存布局，比如把原始的二进制格式在运行前就利用工具做好数据布局处理，而非载入时才处理

==== 7.2.2.4 GUID(全局唯一识别码)

用来全局唯一的标识出资源。最常见的GUID就是把资源的文件路径(或32位哈希值)当作GUID。优点是直观，且能保证唯一性

但有些引擎会使用比如128位hash，然后利用工具保证唯一性。

在虚幻3里，由于资源会存储在包里，故包文件的路径不能唯一识别资源，解决方案是包内的资源按文件夹结构组织，并让资源取唯一的名字，故虚幻里的资源GUID格式是由包名+包内的资源路径拼接出来的

==== 7.2.2.5 资源注册表

大部分资源管理器内都会有某种形式的资源注册表，用来记录已载入的资源，最简单的做法就是用字典(即KV键值对)的集合来实现。键为唯一标识符，值就是指向内存中资源的指针。

当资源加载时，用GUID为键，加入到资源注册表中，卸载时，就会删除注册表记录

当游戏请求资源时，资源管理器会先用GUID查找注册表，若查到，则传回资源指针，否则，自动载入资源，或者返回失败码

由于资源载入是缓慢的操作，在运行时载入很可能影响帧率，有两种方法优化:

. 游戏进行时禁止加载资源，即资源加载画面，实现简单
. 异步，流式，后台加载，但是实现较难

==== 7.2.2.6 资源的生命周期

资源可以自动或手动管理生命周期

每种资源的生命周期不同：

. 全局驻留直到整体结束,比如玩家角色的mesh, texture，或HUD，字体等
. 关卡范围内的资源，随关卡加载诞生，关卡结束销毁
. 关卡内的一次性资源，比如过场动画等
. 动态资源，没有固定的生命周期，如背景音乐，音效等，一般按块载入，块大小根据硬件情况来定。比如：音轨某一时刻只需要两块数据，一块是播放中的，另一块是紧接着要播放的。

资源的加载时机一般容易确定，但是销毁不确定，可以用引用计数实现

资源加载的目的地不同：

. 加载到显存中的资源：比如texture, vertex buffer, index buffer, shader等
. 加载到内存中的资源，也可能按生命周期范围不同，存储在不同的内存地址区间里，与资源管理如何设计有关

==== 7.2.2.7 资源内存管理

分配时，需要尽量避免内存碎片，方法如下:

. 基于堆进行资源分配
.. 忽略内存碎片，让操作系统通过虚拟内存分配，帮你把物理内存映射为连续的虚拟内存空间，缓解内存碎片的问题
.. 定期整理内存碎片，比如是在游戏机而不是家用电脑上
. 基于栈进行资源分配, 内存自然连续，且释放是以反方向进行，有强顺序时适用
.. 游戏是线性且以是基于关卡的，有强顺序加载逻辑时
.. 内存足够容纳整个关卡
.. 还有双端栈分配
... 底端用来载入持久数据，顶端用来为每帧分配临时内存
... 或者顶端是下一个关卡压缩后的数据，底端是当前关卡解压后的数据，当进入下一个关卡时，释放A,并发B解压至底端，由于解压通常比硬盘读入快得多，可大幅降低载入时间
. 基于池进行资源分配
.. 把资源数据以同等大小的块载入，此法也不会有内存碎片，但是需要资源可以切分成同等大小
.. 缺点是可能有空间浪费，除非资源正好是块的整数倍，特别是最后一个块浪费空间可能较多
.. 可以把块的大小设置为OS的IO buffer大小的整数倍以期望在载入时优化性能
... 一种称之为chunk allocator的分配器，即按块分配内存，用链表关联彼此
.... 配合chunk allocator的资源文件，可能被分段，每段分为多个chunk,方便进行内存分配，段按照用途和目的地区分，可能留作内存数据，另一端可能是临时数据等

==== 7.2.2.9 处理资源间的交叉引用

用C++的指针或引用并不够用，因为只表示内存地址，只能在运行时，加载时确定，有两种方案:

. 使用GUID做识别符，要求每个资源都要有GUID,资源管理器要维护资源表，根据GUID能够查到对应指针
. 指针修正表:把指针转换成文件的偏移量，使用时，先把引用到的文件访问一次，然后把对象的内存镜像(image)写到文件中,就是把对象的镜像序列化成连续的文件，这个文件里记录了对象的内存地址偏移值，载入时把偏移转回指针
.. 注意平台差异可能会导致指针偏移值不兼容
.. 对资源内部的引用有效，对外部资源，还要加上资源所属文件的路径

==== 7.2.2.10 载入后初始化

一个资源在构造时不方便也无法避免的步骤，需要放在构造完，并在运行时进行初始化操作，理由:

. GPU资源初始化不同于CPU资源初始化：比如顶点和索引buffer，载入内存后，要在渲染前传到显存，只能在运行时加载前才能执行，而不是构造时，构造只能负责在内存里的数据
. 可以但不方便的操作，能更灵活: 比如想暂时现在运行时而不是构造时处理的数据