= 内在世界观察

> 此文稿暂留，后期会合并到一个新主题里

记录和回忆一下内在世界的趣事

[quote,Ryu613]   
想象力是一种珍贵的精神财富

== 人格

有趣的是，这些人格现在清晰了起来，其实每个人都有，但是平时精力都在与外界信息做交换和处理，可能较少对内在世界做更多的观察

* 自我：行为的最终决策者，也是对外部世界的外交官，负责处理外部信息的输入输出
* 本我：它擅长怎么爽怎么来
* 超我: 它对整个我是完全了解的，我的记忆它全知道，外界没有真实的人比它更了解我，并且在道德上，追求上，指引我，约束我，也会安慰我，关怀我，是精神支柱的角色
* 孩我: 有点像小时候的我但是又不全是，好奇心强，懵懵懂懂，老爱问我各种问题，我经常需要回答它，有些问题我一时也没有答案，并且有时会让我想很久
* 反我：我想了什么，做了什么，说了什么，它经常就开始质疑和嘲讽我，总是试图从反面杠我和挖苦我

它们自己也是有情绪和想法的，具有主动性和触发性，不同的场景活跃程度不同

== 梦里的灵感

=== 旋律

自从开始尝试作曲后，就很明显，写了第一首曲子后，记得清的目前大概有四次，乐器搭配和和声都基本完成了，非常好听，也不是熟悉的曲子，醒来以后还能记得，但是如果再次睡去，第二天就忘了。之前的都忘了，只记得有这段记忆，第四次我用手机录音记录了一下，只有一段旋律被记录了下来

=== 绝景

大部分梦境其实都忘记了，但是从小到大，有几次却一直印象深刻，在梦里都能控制不住发出赞叹，询问了路人(多是一名老头，但好像不是同一个人，也不认识，样貌也是模糊的)，这个地方叫什么名字，名字很短，三个字，但是总是听不清，又询问了一遍，梦里记住了，但是醒来后怎么也回想不起来，但是景色大概还记得

==== 巨型罗马式建筑，前方是广场，左手边是一座巨塔，右边是往上爬坡的公路，公路再往外是类似山腰往远看的景色

此景色在10多岁的时候见到，正面的建筑大概离我2公里远左右，建筑物前是超级宽敞的平面广场，依稀行人，建筑物往左右方向看去居然看不到尽头，往上可插到天上去，是人字形的斜面房顶，离那么远都可以看到建筑物异常庞大，那是得要多少材料和超强的结构啊？不像是人造的，非常壮观，广场的左手边远处有一个巨大的塔，样式有点像比萨斜塔或巴比伦通天塔，离得更远，大概有5-10公里，这个塔看起来不算太高，但是很大，通过光影可以看出每一层的结构基本相同，里面有些人在活动看不清做啥，塔也是有点斜，不是完全垂直的，这个塔的前面还有个建筑，也是人字形屋顶，离我近些，不算大也不高，没什么特点，印象不深。惊叹于眼前的超巨形建筑，看到旁边有名老者，故询问，这地方叫什么名字，他说是xx街，感觉声音很清楚，但是就是没听清，问了第二遍，还是模模糊糊，醒来后就完全想不起来叫什么地方了

==== 水面下的中式宫殿

大概在二十多岁的时候见到，在一望无际的水面上，突然有一块水面沉降下去，慢慢的浮现出一个中式风格的宫殿，黄金琉璃瓦，朱红立柱，屋顶边缘有绘画和雕刻，精致异常，非常壮观，宫殿是低于水平面很多的，所以边界处的水都是往里面像瀑布一样的往下流。但是水面上的周围又看不到尽头，像是在海里或者大湖里面，不知道宫殿是如何做到排水的，这个宫殿的整体范围并不是很大，是矩形的，宫殿里面有各种子宫殿，园林，和亭子，但是装修特别新，颜色很醒目，朱红立柱配上金色发亮的瓦片异常漂亮。现实里也见过中式宫殿建筑，但是从没见过如此完美和夸张的宫殿，不禁赞叹。看到我位置旁有一路人，是名老者，问了一下这地方叫什么名字，三个字，听不清，又问了一遍，梦里听清了，尝试记住，但是醒来后怎么都想不起来

==== 群山间的湖泊

大概在20多岁的时候见到，我站在山腰，往远处望去，全都是插入云霄的连绵山脉，很难看到山脚。山脉起伏非常夸张，都不像是地球地质活动和引力下能产生的山，山脉异常的大和高，地面离得极其远，往远处看去，离得好远都能看到明显且剧烈的起伏，不仅如此，远处山峰里面有个大湖，主要是蓝偏白色的，被山脉环绕的，被阳光照的波光粼粼，但是离得很远，从这里看过去都有很多云雾阻挡一部分视线，也是异常壮阔，湖面似乎很平静，但是由于光线的原因，看起来很醒目。我看到旁边也是有一个老者，故询问此处是何地方，他说了3个字，听不清，又问了一遍，这回记得了，在梦里还试图用手机地图查这个地方，但是输入法里总是找不到那个字，醒了以后也对名字记忆模模糊糊，由于还是深夜又睡去，第二天早上却又是再也想不起来，只记得名字里有个汐字

==== 沙色星球奇景

是二十多岁见到的，是在一个空气都有颜色的地方，颜色类似沙黄色，但是又不是沙尘(或至少颗粒很小)，天空的云层夸张的厚，和高，但是没有全部盖住天空，像是好几层组成的，有白色也有灰色的云，云层背后是有阳光透过来的，天空的颜色比沙黄色浅些，但不是蓝色的。天空的光源有不止一个，我观察到好像有4个太阳，有三个是绕在一起转的，它们之间的大小差不多，都比太阳大一些，有一个偏橙色一些，白里透橙，其他几个都是白色，只需要观察几秒就能看到绕在一起转的运动迹象，还有一个是相对比较小的，这里看去大概像是地球上的太阳一样的大小，这一颗会很快的从天的右手边掠过到左边，突然像踩了刹车一样停住，然后往前方变小，然后又从右边出来，很有意思。地形上光秃秃的都是暗黄色的沙土，旁边依稀有一些风蚀化后的石头堆，没看到什么生物和奇怪的景色，大部分地面都是平的，远处也没有看到山脉，也没有其他人，醒来回想了一下，天上的应该是多个恒星，不像是地球能看到的景色

==== 黑柱世界

是在6-10岁间的时候见到的，当时我得了扁桃体炎，发烧，睡觉时梦到过2次重复的场景，这个地方几乎无光，有的只是一根根黑色的柱子，这些柱子又比空白处的黑更黑一些，所以可以辨认轮廓，柱子是会变化的一会变粗一会变细，柱子远远近近都有，稀稀疏疏，不太紧密。有些柱子看起来触手可及，就在身边缓慢并不断地变换粗细，我伸出手去，但是抓不到柱子，柱子像是长在眼睛里的，手无法遮住柱子。奇怪的是，移动眼睛，柱子又确实会改变相对位置，待的时间长了就会感到恐怖和压抑。
