= {cpp} core guideline
:toc: left
:toc-title: 目录

====
只记录本人觉得有意义和印象深刻的部分

基于Rainer Grimm写的书

第一遍先速读，把所有条款看一遍，然后筛选出有启发的和暂时不懂的部分即可

前言吹嘘此书的翻译，我读下来略感失望，语序和表达很多都没有按中文调整，说是为了保持原作者原意更多的成为了一个借口

此书我比较看重的是原作者grimm对guideline经书做了挑选和解读，之前看过他写的pmr介绍，算是很通俗易懂，印象很好，也有个人网站，写的不错。中文毕竟母语读起来快，现在看起来有点效果，但是翻译水平实际很一般，还不如我之前自己翻pbr4的水平，又不敢意译(或是怕说多易错，毕竟cpp面对的场景很多，无法避免以偏概全，要么就得用一堆高抽象的指代词重新涵盖所有概念，又会造成读者阅读负担)，

总的来说，略感不值(英文未引进的版本又太贵，能看开源免费的好资料还是优先，但是其成本在于需要时间去查询，筛选和试看，我自己遇到很多试看才会遇到的问题，比如看到一半发现资料有坑(没写完，或者虎头蛇尾质量骤降，或者有错漏给人走弯路或调试半天，或者早已过时或弃用的内容)的免费资料不少，自己时间花出去了，还没法指责, 因为作者确实为爱发电付出不少，真正精品的免费资料都得自己亲自花时间整理)

但是有一点也想提，即: 没有完美的资料，没法的，只能多个资料一起对比着看看

有空看看原著，这个项目属于一直更新的状态
link:https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines[cpp core guidelines]

第一轮主要心得，概括来说:

. 除了总结出来的重点外，要多熟悉stl特别是容器和算法，其次了解boost，然后把guideline的静态检查工具打开，比如VS的代码分析或clang-tidy
. 需要重复或后续再读的章节
.. 4，5: 最大体会就是应该用{cpp}语法来表达语义，实际上是有很大关联的，但是现在很多资料只讲语法，这本书就能补充一些语义知识
.. 弟9,17: 主题很好，但书里太泛，回头扩展看看原文和其他资料
.. 10，13是并发和模板元编程，暂时需求没那么高，搁置
. 这本大部分不用细读，读一遍总结一下重点和可以扩展学习的点即可
. 个人还需要补充: stl, boost, lambda, 并发，模板

====

:leveloffset: +1

include::ch2.adoc[]

include::ch3.adoc[]

include::ch4.adoc[]

include::ch5.adoc[]

include::ch6.adoc[]

include::ch7.adoc[]

include::ch8.adoc[]

include::ch9.adoc[]

include::ch10.adoc[]

include::ch11.adoc[]

include::ch12.adoc[]

include::ch13.adoc[]

include::ch14.adoc[]

include::ch15.adoc[]

include::ch16.adoc[]

include::ch17.adoc[]

include::ch18.adoc[]

include::ch19.adoc[]

include::ch20.adoc[]

:leveloffset: -1

