= 让信息工具能帮助每一个人

> 这是一个初步构想，每一个主题都可以展开成更具体的内容

> 必须尽量言简意赅，通俗易懂，非必要不展开

== 信息环境的构想

指人接收到的所有信息构成的环境，特别是网络信息。有的人就如同住在沙漠里，有的人就像在深山老林里，总的来说，大部分人都像野人一般过着信息生活，这是由于互联网带来的信息繁荣的时代尚处于初级，缺少对信息环境进行更好的控制的观念和工具导致的

== 观点

- 只有廉价和简单的工具出现，才能真正改变更多人的信息环境，单纯靠制度，企业的自我约束，是不行的
- 利用从众和向好心理，把使用这种(类)工具的人看成更好，更优秀的人，才能使更多的人想要使用这种工具
- 工具拥有者必须掌握在使用者自己手中，必须能够轻易获得或创造出来
- 工具的使用必须为用户带来正向反馈，缺乏正向反馈的话，帮助的程度和范围就会很有限，即便是工具真的很好
- 只有非盈利化，和透明化才能保证工具的纯粹性
- 没有事物是能一直不变的，也没有事物是永远正确的。生物学给的启发是：死亡机制和演化机制，可以利用仿生学
- 必须时刻注意务实，可实现，逐步升级，避免过度理想化

== 信息树设想

神话故事里经常有的一种设定，就是各种种族都是在一棵神树下生活的，信息环境下，有这么一颗大树，它代表了全人类对世界的认识，树枝和树干就是知识的索引，树叶就是具体的知识，这棵树是会成长的，它的生命周期比起子孙树来说要长

神树下，有各种独立的小树，它们是神树的子孙，具有死亡和演化机制，子孙树和神树，可以互相转化

> 本质上是一个信息净化和蒸馏器，用仿生手段去演化和迭代，建立足够可靠的信息源，生长没有直接依赖，也是压缩即智能，和演化论的体现

=== 信息树的初步设计设想

. 对生命的模拟，如死亡，演化，繁殖
. 对环境的模拟，即信息环境
. 对"助人为乐"的模拟
. 具备理解和被理解特性
. 具备信息筛选和蒸馏能力

=== 信息树实现

高关联领域：AI， wiki，系统科学，编程，计算机网络，数据治理，信息学

=== 实验性原型demo设计

初步调研:

. 开源llvm
. 开源仿生工程和自迭代方法
. 信息环境，信息可靠度建模方法
. 知识度量方法，知识图谱建模
. 数据持久化方案
. 数据采集方法，爬虫
. 数据蒸馏和压缩方法
. 可以考虑接入的api

== 知识度/信息度量

    指一个工具，可以衡量一个人在各个领域的认识情况，偏好，和期望，这是为了更好的进行信息生活

    信息度量不应该交由人工完成，应该自动化

    为什么互联网交流质量低下，比较大的原因就是交流的双方的认识水平没有在一个层次上，所以对主题的理解都不一样

== 知识索引

    信息树的枝干，暂不展开，通俗来讲可看作wiki的多模态，动态生成，仿生，助人为乐特性的加强版

== 认识同步器

    指一种机制，在参与交流前由主题创建者决定是否采用，若采用，则交流者必须满足知识测量的某些指标才能参与，目的是为了提高交流质量

== 信息精粹

    指一种工具，对信息进行筛选和精炼，并分门别类的加到知识索引下，少而精，言简意赅，通俗易懂，而且是无限迭代的，多版本的，多模态的，可与知识度测量接合，这样才能进行更好的适配

== 虚拟身份

    比帐号体系更具体和更大的虚拟身份，身份工具必须掌握在每个人自己手里，不由机构或公司控制, 必须由个人决定是否交出,即便交出也只是一种快照，并且原生具有时效性，获取检测和不可拷贝性，过期或者已被识别后自动销毁，不由用户或机构决定。虚拟身份可以包含多个具体的各种账号，由身份统一管理
    
    虚拟身份可以新建和删除，虚拟身份包含了以下信息:

    - 子身份的知识量度信息，根据期望选择后测量出来的相关领域的认识程度和分布
    - 期望, 比如成为什么样的人，想成为什么职业，想学什么，想玩什么
    - 其他相关信息

